version: '3'

services:
  postgresdb:
    image: postgres:13
    environment:
      POSTGRES_DB: omnichannel_management
      POSTGRES_USER: ahona
      POSTGRES_PASSWORD: ahona
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ahona
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
    volumes:
      - pgadmin-data:/root/.pgadmin

volumes:
  postgres-data:
  pgadmin-data:
